openapi: 3.0.0
info:
  title: Quiz API
  version: 1.0.0
paths:
  /generate-qr:
    post:
      summary: Generate QR Code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    user_id:
                      type: integer
      responses:
        '200':
          description: QR Code generated successfully
        '400':
          description: Bad request

  /question/{user-id}{quiz-id}{question-id}:
    delete:
      summary: Delete a question from a quiz
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the user
        - name: quiz-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the quiz containing the question
        - name: question-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the question to be deleted
      responses:
        '200':
          description: Question deleted successfully
        '400':
          description: Bad request
        '403':
          description: Unauthorized
        '404':
          description: Question or quiz not found
        '500':
          description: Internal server error

  /quiz/{user-id}{quiz-id}:
    get:
      summary: Get quiz by ID
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the user
        - name: quiz-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the quiz to retrieve
      responses:
        '200':
          description: Quiz retrieved successfully
        '400':
          description: Bad request
        '403':
          description: Unauthorized
        '404':
          description: Quiz not found

    put:
      summary: Update quiz title
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the user
        - name: quiz-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the quiz to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new-title:
                  type: string
                  description: The new title for the quiz
      responses:
        '200':
          description: Quiz title updated successfully
        '400':
          description: Bad request
        '403':
          description: Unauthorized
        '404':
          description: Quiz not found
        '500':
          description: Internal server error

  
    delete:
      summary: Delete a quiz
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the user
        - name: quiz-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the quiz to delete
      responses:
        '200':
          description: Quiz deleted successfully
        '400':
          description: Bad request
        '403':
          description: Unauthorized
        '404':
          description: Quiz not found
        '500':
          description: Internal server error

  /quiz-list/{user-id}:
    get:
      summary: Get list of quizzes for a user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the user
      responses:
        '200':
          description: Quiz list retrieved successfully
        '400':
          description: Bad request
        '403':
          description: Unauthorized
        '404':
          description: Quizzes not found
