/*https://editor.swagger.io/*/
openapi: 3.0.0
info:
  title: Your API Title
  description: Description of your API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Handles user login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
                  token:
                    type: string
        '400':
          description: Invalid password or missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /register:
    post:
      summary: Handles user registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
              required:
                - username
                - password
                - email
      responses:
        '200':
          description: Successful registration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  user_id:
                    type: integer
                  token:
                    type: string
        '400':
          description: Username or email already exists or missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /passwordChange:
    post:
      summary: Handles password change
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idUser:
                  type: integer
                password:
                  type: string
                newPassword:
                  type: string
              required:
                - idUser
                - password
                - newPassword
      responses:
        '200':
          description: Successful password change
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      email:
                        type: string
        '400':
          description: Invalid current password or missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: User not found or password change request expired
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
