openapi: 3.0.0
info:
  title: Quiz API
  version: 1.0.0
paths:

  /generate-qr:
    post:
      tags:
        - Quiz
      summary: Generate QR Code for Quiz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    subject:
                      type: string
                    user_id:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          question:
                            type: string
                          isOpenAnswer:
                            type: boolean
                          options:
                            type: array
                            items:
                              type: object
                              properties:
                                label:
                                  type: string
                                isCorrect:
                                  type: boolean
      responses:
        "200":
          description: QR Code generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  image:
                    type: string
                  qr_code:
                    type: string

    get:
      summary: Get QR code by code
      description: Retrieve QR code image based on the provided code.
      parameters:
        - in: query
          name: code
          required: true
          description: The code to generate the QR code.
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  image:
                    type: string
                    format: binary
                    description: Base64-encoded QR code image.
                  qr_code:
                    type: string
                    description: Generated QR code URL.
  /question:
    put:
      summary: Update Question (To be implemented)
      responses:
        '501':
          description: Not implemented
          
    delete:
      summary: Delete a question from a quiz
      parameters:
        - name: user-id
          in: query
          required: true
          schema:
            type: integer
          description: The ID of the user
        - name: quiz-id
          in: query
          required: true
          schema:
            type: integer
          description: The ID of the quiz containing the question
        - name: question-id
          in: query
          required: true
          schema:
            type: integer
          description: The ID of the question to be deleted
      responses:
        '200':
          description: Question deleted successfully

  /quiz:
    get:
      summary: Get quiz details by ID
      parameters:
        - name: quiz-id
          in: query
          description: ID of the quiz to retrieve
          required: true
          schema:
            type: integer
            format: int32
        - name: user-id
          in: query
          description: ID of the user who owns the quiz
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  quiz_id:
                    type: integer
                    format: int32
                  user_id:
                    type: integer
                    format: int32
                  quiz_title:
                    type: string
                  quiz_description:
                    type: string
                  quiz_created_at:
                    type: string
                    format: date-time
                  quiz_code:
                    type: string
                  subject:
                    type: string
                  questions:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        question_text:
                          type: string
                        open_question:
                          type: boolean
                        options:
                          type: array
                          items:
                            type: object
                            properties:
                              option_id:
                                type: integer
                                format: int32
                              option_text:
                                type: string
                              is_correct:
                                type: boolean
                              context:
                                type: string

    put:
      summary: Update Quiz Title
      parameters:
        - name: quiz-id
          in: query
          schema:
            type: string
        - name: user-id
          in: query
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new-title:
                  type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string

    delete:
      summary: Delete Quiz
      parameters:
        - in: query
          name: user-id
          schema:
            type: integer
          required: true
        - in: query
          name: quiz-id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Quiz deleted successfully

  /quiz-list:
    get:
      summary: Get a list of quizzes
      description: Retrieves a list of quizzes for the specified user.
      parameters:
        - name: user-id
          in: query
          description: The ID of the user whose quizzes to retrieve
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A list of quizzes
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        quiz_id:
                          type: integer
                          description: The ID of the quiz
                        title:
                          type: string
                          description: The title of the quiz
                        description:
                          type: string
                          description: The description of the quiz
                        created_at:
                          type: string
                          format: date-time
                          description: The creation date and time of the quiz
                        code:
                          type: string
                          description: The code of the quiz
                        subject_id:
                          type: integer
                          description: The ID of the subject of the quiz
