openapi: 3.0.0
info:
  title: Vote API
  version: 1.0.0
paths:
  /start-vote:
    post:
      summary: Start a vote for a quiz
      description: Start a vote for a quiz identified by its ID
      parameters:
        - in: query
          name: user-id
          description: The ID of the user initiating the vote
          schema:
            type: integer
            format: int64
          required: true
        - in: query
          name: quiz-id
          description: The ID of the quiz to start the vote for
          schema:
            type: integer
            format: int64
          required: true
      responses:
        '200':
          description: Vote started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Vote started successfully